# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abdbad2e17a5bdcdbf6b27a3fb04826d8c1733a5238af9b846f1f5b85c698e52ae139516db9d5a4e91ceba980e865805e84fa33e6449b28ba54bfe501b9e1560

test:
  secret_key_base: 664f26ef0f1b2deac33987f67475bf73f34cb3239fefa4f190945d0e652d4844b09f0da4f0eeeb05ef26b8239b6591fc81af45c12afe421494864bce6c6a510a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
